### ISSUE TITLE
Travis Test for Migration scripts

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/db#106]
We should add tests for the migration scripts,
currently the migration is running on an empty database.

**Comment by micheljung** [comment]
We would need to insert data before each migration step with various combination, I don't think that it's viable to do this.
At leats I added the test-data import to the build https://github.com/FAForever/db/commit/b2e9f094c8229359ee8d644b88bbcc374dbea144

**Comment by IDragonfire** [comment]
My simple idea was to have a small test dump on version 1 and run all migrations. This will not detect all errors like @micheljung mention but maybe some ...

Sample for false positive: `add nullable column`  in v5 `make column not null` in v6 potential lead to failing migration the column may have null values ...

PS.: I also updated the wiki: https://github.com/FAForever/db/wiki/How-to-Contribute#tipps-to-get-your-pr-approved

**Comment by Brutus5000** [comment]
Test-data.sql is imported during CI run.
