### ISSUE TITLE
Rework `matchmaker_ban`

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/db#109]
I found the table `matchmaker_ban`

Is this feature used?
https://github.com/FAForever/server/blob/f5c056263fddde5edc4c7927abed61d0fd91e718/server/lobbyconnection.py#L922

# Suggestion
Move to `ban` table and replace by view ...
https://github.com/FAForever/db/issues/51

**Comment by Askaholic** [comment]
This table can be removed now

**Comment by Brutus5000** [comment]
Table dropped in https://github.com/FAForever/db/commit/88b57258a81bad4f3c1f17b4afc7d41413c0071b
