### ISSUE TITLE
lobby_ban must not give more than one ban per user

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#123]
When it was a table, `lobby_ban.idUser` was unique. Since it has been converted into a view, this is no longer the case, so it can return more than one row per user.

Combined with [this server code](https://github.com/FAForever/server/blob/ba7ab5ccc57378ec7e5b68891701d68aadf260b0/server/lobbyconnection.py#L517), this causes users who have been banned more than once to not be able to log in.

**Comment by IDragonfire** [comment]
This should only be the case if the user has more then one active ban, because `lobby_ban` shows only active bans
https://github.com/FAForever/db/blob/develop/migrations/V33__ban-system-ng.sql#L51

**Comment by Sheeo** [comment]
Even if there's more than a single ban row, the server code shouldn't fail and disallow a user who otherwise should've been allowed. Do you have any logs where this happened?

**Comment by micheljung** [comment]
@IDragonfire no, [we fixed that](https://github.com/FAForever/db/blob/develop/migrations/V35__fix-bans.sql) (and it would still lead to the same condition)

@Sheeo the server does, I do not have logs but a user contacted me because he couldn't log in, I tracked the problem down to what's described in the issue.

**Comment by IDragonfire** [comment]
So the server only need the newest ban?

**Comment by micheljung** [comment]
yes, or more specifically, the one with the higher expiration date

**Comment by Sheeo** [comment]
Yes, iff there are multiple bans only the first will be considered as a valid ban. However; I don't see how it would ever deny access due to multiple bans?

**Comment by micheljung** [comment]
The code I linked above joins the user with all its bans. So in case of 2 bans, there are two results. And two results are `!= 1`, so the login is denied.

**Comment by Sheeo** [comment]
We should either use the above commit or write some other code to use the new DB structure. I don't support changing the database or generally leaving these view's in just because of unwillingness to update python code.

**Comment by micheljung** [comment]
I generally agre, but the python server isn't the only one accessing `lobby_ban`. It's also by the python API and (used to be) by the java api. And then there might be some non-public PHP code who accesses it as well, so a (temporary) view allows us to migrate projects gradually instead of having to update update everything in a big-bang fashion.

**Comment by Sheeo** [comment]
I do believe we can let go of the PHP-code at this point? :)

The python API code shouldn't be a big deal to update, either.

**Comment by micheljung** [comment]
So let's close this in favor of #306? And have you checked the PHP code? I'd like to avoid breaking the Map vault.

**Comment by Sheeo** [comment]
Yes, the PHP code doesn't deal with bans any more. Good to close :)
