### ISSUE TITLE
Remove 'is_active'

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#135]
`ladder1v1_rating` and `global_rating` currently have a field `is_active` which needs to be maintained actively by the server - but nothing seems to be in place that sets this field to `0`.

Even if there was, it's a very inefficient solution. Instead, the field should be replaced by a field `last_active`.
All code that uses `is_active` needs to be updated.

As a "quick fix" for the very outdated leaderboard, I set all players inactive who hadn't had their login info changed since 2 months.

**Comment by Brutus5000** [comment]
There is a scheduled job running once a day now to update this.
