### ISSUE TITLE
Disable ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#140]
We have a few applications that fail if `ONLY_FULL_GROUP_BY` is enabled (https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html).

Therefore, we'd like to disable this option. The fix so far has been to manually execute `SET GLOBAL sql_mode = '';` but this also disables any other SQL modes like:
```
STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTIO
```

Which I assume is not wanted.

Let's `select @@sql_mode` and explicitly remove `ONLY_FULL_GROUP_BY`. Then we can set the sql_mode in the mysql config:

```
[mysqld]
sql_mode = "STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

**Comment by Brutus5000** [comment]
Fixed by https://github.com/FAForever/faf-stack/commit/9644192f07ce8c94f0b88ccde81020c466eff1e5 (and on prod as well)
