### ISSUE TITLE
db-structure.sql autogenerate

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/db#15]
db-structure.sql can be automatic generated in the builld process ...

**Comment by Sheeo** [comment]
Does this mean we want to? I wouldn't want travis committing back into this repo and we do want a plain .sql file that's easily runnable to construct the database structure.

**Comment by IDragonfire** [comment]
The current sql file is mostly automatic generated from mysqld...  What is a plain sql file? Ruby on rails for example has such a Schema.sql ...very useful to see of migration working over time... And it is just another task to do by Hand and to check....

**Comment by IDragonfire** [comment]
btw. it must not generated by travis and commited ... can be done by dockerfile at runtime ... or a build script ... I will provide a readme or shell script for it ...
