### ISSUE TITLE
Have a constraints on the message's key

### ISSUE THREAD

**Issue by axel1200** [FAForever/db#165]
@Brutus5000 suggested (https://github.com/FAForever/faf-moderator-client/pull/42#issuecomment-418497060) to have reference constraints on the messages key column in table achievment_definition, tutorials... and all the voting tables. Atm you can also enter key that do not exist.

@micheljung what do you think?

**Comment by axel1200** [comment]
Personally I think that is not needed. The indexes that would be created are not needed as java-api loads them into memory. Anyway they are always different messages with the same key so we would need some costum sql triggers. It would not be the same as a Foreign key constraint. When deleting the messages you would not be warned of existing references etc. And maybe you wanna be able to create objects like tutorial without any keys and have translators make all the messages for you. Anyway you can easily see yourself if the message you entered into exists or not if  it does not exist you are shown the key which you entered as message ;) So I would be for leave it as it is...

**Comment by micheljung** [comment]
@axel1200 @Brutus5000 `messages.key` is not unique so it can't be used as a foreign key (even though MySQL will allow it, things will start to break down once there are non-unique values in the table).

Referencing keys that don't exist is ok, implementations should fall back to the key when no translation can be found.
