### ISSUE TITLE
Add telgram auth information

### ISSUE THREAD

**Issue by axel1200** [FAForever/db#170]
Add a colum to login table with the users telegram id

**Comment by Brutus5000** [comment]
No. This was never the intended solution.

**Comment by axel1200** [comment]
And hash it

**Comment by Brutus5000** [comment]
Don't put it in the user column.

**Comment by axel1200** [comment]
Ok just a column where it says if a user is authenticated via telegram and a table containing hashed user ids from telegram so they can not be used again

**Comment by Brutus5000** [comment]
Won't fix. The requirement has not come up again in the last 12 months.
