### ISSUE TITLE
Change foreign key references in `leaderboard_*` tables to smallint

### ISSUE THREAD

**Issue by Askaholic** [FAForever/db#226]
Does that mean we should changes the primary key of the referenced tables too?

**Comment by norraxx** [comment]
If we have `references` in column definition, we have to move `references` to `key/index` table definition, below column definitions.

Be aware of integrity errors, if there is inconsistent behavior, we shoudl fix them.
If it won't be possible, use `SET FOREIGN_KEY_CHECKS = 0;` before migration, and `SET FOREIGN_KEY_CHECKS = 1;` after migration.
I preffer to fix reference checks.

**Comment by Brutus5000** [comment]
@Askaholic yes, the reference key column has to match.
