### ISSUE TITLE
Fix foreign key constraints

### ISSUE THREAD

**Issue by Askaholic** [FAForever/db#229]
Turns out mysql doesn't honor inline `REFERENCES` declarations, so we need to go back and add foreign key constraints manually for these tables:

- `leaderboard_rating`
- `leaderboard_rating_journal`
- `matchmaker_queue`
- `map_pool_map_version`
- `matchmaker_queue_map_pool`
- `map_reviews_summary`
- `mod_reviews_summary`

I think this has been a pretty common problem, and the cause of several issues over the years as there are a lot of migrations already for adding in missing foreign key constraints.

**Comment by Brutus5000** [comment]
Needed to revert V95 / #230
