### ISSUE TITLE
Change V97 tables/materialized views gather the data from leaderboard_rating

### ISSUE THREAD

**Issue by norraxx** [FAForever/db#236]
Problem:
we've made unwanted migration from `ladder1v1_rating` and `global_rating` to point data to new table `leaderboard_rating`.

Goal:
create views `ladder1v1_rating_rank_view` and `global_rating_rank_view` that will gather data from new table `leaderboard_rating`

**Comment by Brutus5000** [comment]
@norraxx you need to add "closes #236" or "fixes #236" in the commit message to trigger auto-closing the issue after merge.
