### ISSUE TITLE
Sera is coop missions are listed as CUSTOM

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/db#246]
Should have their own category so that the client can show a symbol

**Comment by Askaholic** [comment]
Well that's because they are custom missions. Compared to the other ones which are GPG missions from the base game.

**Comment by 1-alex98** [comment]
Well the only effect that has are the ICONS on the client so I guess making them have a different category would be cool. Maybe CUSTOM_SERAPHIM

**Comment by Brutus5000** [comment]
This was solved in #301
