### ISSUE TITLE
Decrease database load

### ISSUE THREAD

**Issue by norraxx** [FAForever/db#268]
During latest database problems and amount of data in FAF I'm offering to make search views.
And materialize data them once per day/hour/10 minutes.

Query like that:
```
select count(distinct game0_.id) as col_0_0_
from game_stats game0_
         left outer join map_version mapversion1_ on game0_.mapId = mapversion1_.id
         left outer join map map2_ on mapversion1_.map_id = map2_.id
         left outer join game_player_stats playerstat3_ on game0_.id = playerstat3_.gameId
         left outer join login player4_ on playerstat3_.playerId = player4_.id
         left outer join global_rating_rank_view globalrati5_ on player4_.id = globalrati5_.id
where (map2_.display_name like concat('%', 'astro', '%'))
  and (game0_.validity in (0))
  and game0_.endTime >= '2020-01-29 17:32:59.717917'
  and globalrati5_.rating > 1300.0
  and (game0_.endTime is not null);
  ```

Needs 6 tables to get one result.

What I'm proposing is to create/update indexed materialized view with all needed data in it.
So there will be NO join on ANY of other tables.
Or there will be one or max 2 joins on direct/strict conditions, but without ANY filtering on that joined tables.

What should be done
1. think and create one materialized view + update it with some event
2. create new table definition on server for Elide
3. change client to use that new filter

**Comment by Brutus5000** [comment]
You basically suggest to join everything and put it into a flat table. That would more than double the database content with 100 million++ records.

**Comment by norraxx** [comment]
Not necessary. actually we could one to one tables have at one place, and ONLY users would be a problem, there we should think, how to deal with that problem. In onther words, let's have some search table with size of ammout of games.

**Comment by Brutus5000** [comment]
Currently db load is fine
