### ISSUE TITLE
2016-08-08 Database migration

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#28]
- [x] Make sure Server & API are stopped
- [x] Back up database:
```
cd /opt/stable
tar cvpjf db-backup-$(date +"%Y-%m-%d-%H-%M-%S").tar.bz2 db
```
- [x] Merge `origin/develop` into `origin/master`
- [x] Update DB on prod (get root password first):
```
cd /opt/stable/db_repo/
git pull
./migrate.sh
```
Name of docker container: `stable_faf-db_1`
Database to migrate: `faf_lobby`
Current database revision: `ab3d56fe949550d2ac113a148582e4c7c690e25c`

Migration is expected to run successfully: 
```
<noise>
Database is now at revision 5ab8cba965337aa8ec3dc4b5089514e44f834862
```

**Comment by visionik** [comment]
Five ideal things I'd like to see added to any roll-out plan moving forward.  I'm not requiring them now, but we should aspire to have these things.  These are all from lessons learned at my companies during big deployments:

1. Always have a roll-back plan in the to-do list in case the roll-out doesn't work.

2. Always have at least three people on-hand for a roll out:

a) One person doing deployment
b) One person doing testing
c) One person facilitating communications between the users and developers/deployers during and after roll out

3. Always have someone readily available (ie, on slack, on FAF irc) who can do a roll-back or hot-fix for a minimum of 2-3 hours after any deployment.

4. All roll-out / roll-back plans should be peer-reviewed before we take action.

5. In case things go really bad, make sure we are always prepared to fail over to the second FAF server (stable and stabler are the two servers).

Thanks!

-V

**Comment by micheljung** [comment]
I Absolutely agree! But step by step ;-)
