### ISSUE TITLE
Free one core

### ISSUE THREAD

**Issue by norraxx** [FAForever/db#287]
I'm offering to turn this every 30 minutes.
https://github.com/FAForever/db/blob/5433e3cd15a078224dc0ea7247a5c4e4010ea5ba/archive/V86__achievement_statistics_speedup.sql#L54

`# Query_time: 17.625237  Lock_time: 0.000411  Rows_sent: 0  Rows_examined: 4153764`

Imho too much job for simple achievement.

**Comment by Brutus5000** [comment]
Go for it. Kill & rerecrate with 10 minutes.
