### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by boldhedgehog** [FAForever/db#40]
Hi,

I have free time and desire to improve Docker related stuff here.
How can I contribute, is it needed anyways?

PS: This will be a practice for me and I want to help the FAF community. If you would like to know who I am and what I do, please send me a private message (I do not know if it's possible in github)

**Comment by micheljung** [comment]
Hi boldhedgehog and thanks for your offer!

I don't see any need for work on this repository's Dockerfile, also I don't know about any other. What *could* be needed is work on our docker-compose file in order to fire up all necessary parts of the infrastructure. @Sheeo knows more about this.

**Comment by boldhedgehog** [comment]
Just wanted to ask about the Compose file. I can do this too.
@Sheeo please let me know how can I help.

**Comment by micheljung** [comment]
Closing since there is no need for changes in the current Dockerfile.
