### ISSUE TITLE
Fix game_stats.mapId

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#47]
We have a *lot* of `game_stats.mapId` with value `0`. I suspect a casing problem in the respective query on the server (filename upper/lowercase) which needs to be fixed.

After this is sorted out, we should restore as many map IDs as we can by reading the maps from the replay files.

Last step is to decide/change whether mapId should be nullable or not; currently it's not, but players can play maps that aren't in our database (think of map creators). The question is if we want to store such games at all; if yes, then `mapId` needs to be nullable.

**Comment by IDragonfire** [comment]
My Suggestion:
1. Map ID can be null
2. Map ID should be an UUID/GUID

**Comment by micheljung** [comment]
I prefer UUIDs as well but I'm not willing to rewrite it all, in the end there's no big gain :)

**Comment by micheljung** [comment]
GG "Seton's Clutch": https://github.com/FAForever/server/blob/6a2df59f4691ea096101a409c013a9a27dbe60eb/server/gameconnection.py#L279

**Comment by micheljung** [comment]
```
mysql> select count(*) from game_stats where mapId = 0;
+----------+
| count(*) |
+----------+
|   167903 |
+----------+
```

The map name isn't stored in the replay either, it's always empty string (based on 7 probes). So it looks like the map information is unrecoverable for these games.
I don't know exactly why this is, but at least [this](https://github.com/FAForever/server/blob/58a9135d5e4924ee4fdce24323ef8d74b869f147/server/games/game.py#L570) and [this](https://github.com/FAForever/server/blob/6a2df59f4691ea096101a409c013a9a27dbe60eb/server/gameconnection.py#L279) look wrong, and [initializing a foreign key with 0](https://github.com/FAForever/server/blob/58a9135d5e4924ee4fdce24323ef8d74b869f147/server/games/game.py#L121) also isn't a good idea (well, probably the mapId wasn't a foreign key before, or at least there was no constraint for it).
