### ISSUE TITLE
game_player_stats.playerId has no FK constraint on login

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#48]
`game_player_stats.playerId` references `login` but has no constraint set; ~there are players referenced who do no longer exist in `login`~.

Proposed fix:

```
ALTER TABLE game_player_stats ADD CONSTRAINT fk_game_player_stats_player FOREIGN KEY (playerId) REFERENCES login(id);
```

**Comment by Brutus5000** [comment]
I would propose to create one unknown user and update all game_player_stats to reference the dummy user, instead of creating multiple unknown user.

**Comment by micheljung** [comment]
This would lead to inconsistent data (e.g. a player playing against himself)

**Comment by micheljung** [comment]
Ok looks like there is only one player, ID 88884 who got deleted. I manually re-added him
