### ISSUE TITLE
Foreign keys for clan tables

### ISSUE THREAD

**Issue by micheljung** [FAForever/db#55]
Sounds easy, but actually isn't:

```
mysql> select count(*) from clan_members where player_id not in (select id from login);
+----------+
| count(*) |
+----------+
|     1479 |
+----------+

```

Something is awefully wrong.

**Comment by micheljung** [comment]
Looks like there is another DB `fafclans` and everything looks a bit chaotic. I was told that's thanks to ZeP's requirements in the past.
Closing this since there is more work needed than just adding foreign keys.

**Comment by IDragonfire** [comment]
More Background Information:
* Requirement was to have a seperate database and as seperated as possible
* player data where copied in a seperate schema (`fafclans`) 

=> typically bugs for redundant data occure ... e.g. primary keys from fafclans database mixed up with faflobby database

I tried to fix this in https://github.com/FAForever/db/pull/13
but the data is not used and from my view today it can be even more simplified ...

The old (php) clan app use the seperate database ...
The new version did no come live:

https://github.com/FAForever/clans/tree/refactor/bootstrap
https://github.com/FAForever/clans/tree/refactor/flask
https://github.com/FAForever/clans/tree/refactor/foundation

# TODO

- [ ] Decide about new clan app (where to publish, how, framework, ...)
- [ ] Check and run migration
