### ISSUE TITLE
Add checksum to map version

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/db#65]
We have no clean way to map the local map to a map on the server.
because the user can e.g. modify the map locally, the map is not uploaded ...

I suggest to add a checksum column to the map_version table.
Then we can identify local broken maps and also implement a auto update map feature ;)

Please vote with 👍 or 👎

**Comment by Sheikah45** [comment]
Was considering this but as a note I believe we would have to run a checksum on the zip folders which presents a problem as zip folders include the date last modified as compressed information which would change the checksum based on the day the folder was zipped on the user side. Could potentially run the check sum on critical files in the map though.

**Comment by Brutus5000** [comment]
Given the comment of @Sheikah45  it would make more sense to add a file with checksums into the zip file.
In 5 years I have not heard any need of it by map authors or players.
