### ISSUE TITLE
Add Permission System for Mod App

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/db#67]
Requirement from the Mod App Specification

```
Permission System
Not every mod can use every feature
```

I suggest to introduce a classic permission system:
* You ask for a special permission, e.g. `ban.create`, `ban.delete`
* Admins can define roles with a set of permissions, e.g.role `mod` with permission `ban.*, avatar.*`
* Admins can assign permissions or roles to a user

# Step 1
* We introduce Permissions

# Step 2
* We introduce Roles

**Comment by micheljung** [comment]
see also: http://www.erdiagrams.com/datamodel-rbac-idef1x.html

Just a 1min Google. I'm pretty sure we can find existing SQLs or so for some sort of "proven model"

**Comment by IDragonfire** [comment]
http://slackspace.de/articles/roles-permissions-with-spring-security-3/

**Comment by IDragonfire** [comment]
https://github.com/FAForever/db/pull/76
