### ISSUE TITLE
Data and Migration Inquiry

### ISSUE THREAD

**Issue by Raistlfiren** [FAForever/db#9]
Hi,

First question - Should the migrations be ran after importing the initial structure into the database? 

Second Question - Is there anyway we can get more data for the database tables? For example, it would be useful to have some of the rankings and 1v1 data. I am sure Python has a Faker library to create data for the database, but that would take more time then a simple export.

**Comment by Sheeo** [comment]
When adding migrations we also add the structure changes to db-structure.sql, so running migrations after running those ddl's is redundant.

I would like to provide dumps, but I have had other priorities lately.
